# Generated by Django 3.2.4 on 2021-06-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=15)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
